"""empty message

Revision ID: 098e6caab7aa
Revises: 9c9d1b06be29
Create Date: 2023-03-11 04:18:00.342151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098e6caab7aa'
down_revision = '9c9d1b06be29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
