"""empty message

Revision ID: 1666ded56498
Revises: aa7b4734124a
Create Date: 2023-03-20 22:48:28.875823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1666ded56498'
down_revision = 'aa7b4734124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
