"""empty message

Revision ID: 596ab7586806
Revises: 3af4c92e6425
Create Date: 2023-03-12 20:21:11.723318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596ab7586806'
down_revision = '3af4c92e6425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('logo')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
