"""empty message

Revision ID: 5d4422bbdb93
Revises: 30f2ef2ccfe1
Create Date: 2023-04-10 11:21:29.286702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4422bbdb93'
down_revision = '30f2ef2ccfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tuesdayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('tuesdayEnd', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('wednesdayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('wednesdayEnd', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('thursdayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('thursdayEnd', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('fridayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('fridayEnd', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('saturdayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('saturdayEnd', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('sundayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('sundayEnd', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Schedule', schema=None) as batch_op:
        batch_op.drop_column('sundayEnd')
        batch_op.drop_column('sundayStart')
        batch_op.drop_column('saturdayEnd')
        batch_op.drop_column('saturdayStart')
        batch_op.drop_column('fridayEnd')
        batch_op.drop_column('fridayStart')
        batch_op.drop_column('thursdayEnd')
        batch_op.drop_column('thursdayStart')
        batch_op.drop_column('wednesdayEnd')
        batch_op.drop_column('wednesdayStart')
        batch_op.drop_column('tuesdayEnd')
        batch_op.drop_column('tuesdayStart')

    # ### end Alembic commands ###
