"""empty message

Revision ID: 85a630b7a1ee
Revises: 1666ded56498
Create Date: 2023-04-01 01:42:03.660128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85a630b7a1ee'
down_revision = '1666ded56498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Offering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('approx_location', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('image2', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=256), nullable=True),
    sa.Column('startTime', sa.String(length=256), nullable=True),
    sa.Column('endTime', sa.String(length=256), nullable=True),
    sa.Column('resourceId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('schedule')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.drop_table('Schedule')
    op.drop_table('Offering')
    # ### end Alembic commands ###
