"""empty message

Revision ID: b5fca6605f97
Revises: f26b8b7b0dd6
Create Date: 2023-04-07 19:04:30.049780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fca6605f97'
down_revision = 'f26b8b7b0dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Drop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('identification', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('DropOff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DropOff',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"DropOff_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('identification', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DropOff_pkey')
    )
    op.drop_table('Drop')
    # ### end Alembic commands ###
