"""empty message

Revision ID: c1722353b35e
Revises: 098e6caab7aa
Create Date: 2023-03-14 04:58:54.535738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1722353b35e'
down_revision = '098e6caab7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('Resource_organization_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Resource_organization_id_fkey', 'Organization', ['organization_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
