"""empty message

Revision ID: c5f9d81b65e1
Revises: f05bcc352df2
Create Date: 2023-03-10 20:27:52.186753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f9d81b65e1'
down_revision = 'f05bcc352df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_constraint('Resource_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.create_unique_constraint('Resource_phone_key', ['phone'])

    # ### end Alembic commands ###
