"""empty message

Revision ID: ccc7723a5188
Revises: fdbb8f17152a
Create Date: 2023-04-05 17:07:07.885553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc7723a5188'
down_revision = 'fdbb8f17152a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Schedule', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Resource', ['resourceId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
