"""empty message

Revision ID: cdb9a2485fc6
Revises: 828c9f7ddeaf
Create Date: 2023-04-07 14:38:13.561603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb9a2485fc6'
down_revision = '828c9f7ddeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mondayStart', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('mondayEnd', sa.String(length=256), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('day')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('mondayEnd')
        batch_op.drop_column('mondayStart')

    # ### end Alembic commands ###
