"""empty message

Revision ID: d1617b6508e1
Revises: 85a630b7a1ee
Create Date: 2023-04-01 20:54:26.385329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1617b6508e1'
down_revision = '85a630b7a1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Offering', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offering_type', sa.String(length=256), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('picture')

    with op.batch_alter_table('Offering', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('offering_type')

    # ### end Alembic commands ###
