"""empty message

Revision ID: d27282418c2f
Revises: bbdb26feadd1
Create Date: 2023-03-10 18:48:21.761666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27282418c2f'
down_revision = 'bbdb26feadd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
